// Decodes assets/*.png into palette-indexed sheets in src/sprites.gen.ts, so the plugin
// embeds raw sprites and never decodes PNG. Any colour not in palette.hex fails the build.
// Only 8-bit RGBA, non-interlaced PNGs are supported, which is what the assets are.

import { readFileSync, writeFileSync } from "node:fs";
import { inflateSync } from "node:zlib";

const root = new URL("..", import.meta.url);
const read = (path) => readFileSync(new URL(path, root));

const palette = read("assets/palette.hex")
  .toString()
  .split("\n")
  .map((line) => line.trim())
  .filter(Boolean)
  .map((line) => parseInt(line.replace(/^#/, ""), 16));

function decodePng(name) {
  const png = read(`assets/${name}.png`);
  let width = 0, height = 0;
  const idat = [];
  for (let at = 8; at < png.length; ) {
    const length = png.readUInt32BE(at);
    const type = png.toString("latin1", at + 4, at + 8);
    const data = png.subarray(at + 8, at + 8 + length);
    if (type === "IHDR") {
      width = data.readUInt32BE(0);
      height = data.readUInt32BE(4);
      if (data[8] !== 8 || data[9] !== 6 || data[12] !== 0) throw new Error(`${name}.png must be 8-bit RGBA, not interlaced`);
    } else if (type === "IDAT") {
      idat.push(data);
    }
    at += 12 + length;
  }
  const raw = inflateSync(Buffer.concat(idat));
  const stride = width * 4;
  const rgba = Buffer.alloc(stride * height);
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)];
    const line = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    for (let x = 0; x < stride; x++) {
      const a = x >= 4 ? rgba[y * stride + x - 4] : 0;
      const b = y > 0 ? rgba[(y - 1) * stride + x] : 0;
      const c = x >= 4 && y > 0 ? rgba[(y - 1) * stride + x - 4] : 0;
      let predictor = 0;
      if (filter === 1) predictor = a;
      else if (filter === 2) predictor = b;
      else if (filter === 3) predictor = (a + b) >> 1;
      else if (filter === 4) {
        const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
        predictor = pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
      }
      rgba[y * stride + x] = (line[x] + predictor) & 0xff;
    }
  }
  return { width, height, rgba };
}

// Index 0 is transparent; palette.hex line i is index i + 1. Each index is stored as one
// character, decoded once at activation.
const OFFSET = 48;
let out = "// Generated by scripts/sprites.mjs from assets/. Do not edit.\n";
out += 'import { sheet } from "./sheet.ts";\n\n';
out += "/** RGBA as little-endian u32; index 0 is transparent. */\n";
const packed = palette.map((rgb) => "0x" + ((0xff000000 | ((rgb & 0xff) << 16) | (rgb & 0xff00) | (rgb >> 16)) >>> 0).toString(16));
out += `export const PALETTE = new Uint32Array([0, ${packed.join(", ")}]);\n`;
for (const name of ["characters", "furniture", "overlays", "font"]) {
  const { width, height, rgba } = decodePng(name);
  let indices = "";
  for (let i = 0; i < width * height; i++) {
    const px = rgba.subarray(i * 4, i * 4 + 4);
    let index = 0;
    if (px[3] !== 0) {
      const rgb = (px[0] << 16) | (px[1] << 8) | px[2];
      index = palette.indexOf(rgb) + 1;
      if (index === 0) {
        throw new Error(`${name}.png (${i % width}, ${Math.floor(i / width)}) uses #${rgb.toString(16).padStart(6, "0")}, not in palette.hex`);
      }
    }
    indices += String.fromCharCode(OFFSET + index);
  }
  out += `export const ${name.toUpperCase()} = sheet(${width}, ${height}, ${JSON.stringify(indices)});\n`;
}
writeFileSync(new URL("src/sprites.gen.ts", root), out);
